;
; File generated by cc65 v 2.19 - Git 06d423d50
;
	.fopt		compiler,"cc65 v 2.19 - Git 06d423d50"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_io_init
	.import		_io_disp
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp1
	jsr     _io_init
L0002:	lda     #$01
	jsr     _io_disp
	lda     #$02
	jsr     _io_disp
	lda     #$04
	jsr     _io_disp
	lda     #$08
	jsr     _io_disp
	lda     #$10
	jsr     _io_disp
	lda     #$20
	jsr     _io_disp
	lda     #$40
	jsr     _io_disp
	lda     #$80
	jsr     _io_disp
	bra     L0002

.endproc

